version: '2'
services:
  ddjnode:
    image: dltdojo/node:8
    command: tail -f /dev/null
    volumes:
      - ./ddjnode:/opt/ddjnode
  httpd:
    build: httpd
    ports:
      - "8080:80"
    volumes:
      - ./httpd/html:/usr/share/nginx/html
  backend:
    build: backend
    ports:
      - "8081:80"
    volumes:
      - ./backend/html:/var/www/html
  db:
    image: mariadb:10.1
    environment:
      - MYSQL_ROOT_PASSWORD=root
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_HOST=db
    ports:
      - "8088:80"